#!/usr/bin/env python3
"""
GREMAC Betriebsanleitungen – Build-Script
==========================================
Single Source of Truth: PocketBase (kb_manuals, kb_blocks, kb_structure)

Dieses Script:
1. Holt alle Manuals + Blöcke aus PocketBase
2. Generiert Hugo-Markdown-Dateien (DE+EN) in /var/www/gremac.net/content/betriebsanleitungen/
3. Bettet Bilder als <img>-Tags ein (aus images-Feld des Blocks)
4. Führt `hugo --minify` aus

Verwendung:
    python3 build_manuals.py [--no-build]  # --no-build: nur Markdown generieren

WICHTIG: Markdown-Dateien NIEMALS manuell bearbeiten!
         Änderungen immer in PocketBase vornehmen, dann dieses Script ausführen.
"""

import json
import os
import subprocess
import sys
import urllib.request
import urllib.parse
from datetime import datetime

# ─── Konfiguration ────────────────────────────────────────────────────────────

PB_URL       = "http://localhost:8090"
PB_EMAIL     = "admin@gremac.net"
PB_PASSWORD  = "Gremac2026!"
HUGO_ROOT    = "/var/www/gremac.net"
OUTPUT_DIR   = f"{HUGO_ROOT}/content/betriebsanleitungen"
IMAGES_BASE  = "/images/manuals"   # Pfad wie Hugo ihn sieht (relativ zu /static)

IMG_STYLE = (
    'max-width:100%;height:auto;border-radius:6px;'
    'margin:1.5rem 0;box-shadow:0 2px 10px rgba(0,0,0,.12);display:block;'
)

# ─── PocketBase API ───────────────────────────────────────────────────────────

def pb_request(path, method="GET", data=None, token=None):
    url = f"{PB_URL}{path}"
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = token
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())

def get_token():
    resp = pb_request(
        "/api/collections/_superusers/auth-with-password",
        method="POST",
        data={"identity": PB_EMAIL, "password": PB_PASSWORD}
    )
    return resp["token"]

def get_all_records(collection, token=None, per_page=500):
    """Alle Records einer Collection holen (paginiert)."""
    page = 1
    items = []
    while True:
        path = f"/api/collections/{collection}/records?perPage={per_page}&page={page}"
        resp = pb_request(path, token=token)
        items.extend(resp.get("items", []))
        if len(items) >= resp.get("totalItems", 0):
            break
        page += 1
    return items

# ─── Bildgenerierung ──────────────────────────────────────────────────────────

def render_images(images, alt_de, alt_en, lang):
    """Gibt <img>-Tags für alle Bilder eines Blocks zurück."""
    if not images:
        return ""
    
    if isinstance(images, str):
        try:
            images = json.loads(images)
        except Exception:
            images = [images]
    
    if not isinstance(images, list):
        images = [images]
    
    alt_texts = (alt_de if lang == "de" else alt_en) or ""
    # Alt-Texte: kommagetrennt, einer pro Bild
    alts = [a.strip() for a in alt_texts.split("|")] if alt_texts else []
    
    html = ""
    for i, img in enumerate(images):
        if not img:
            continue
        # Pfad normalisieren
        if not img.startswith("/"):
            img = f"{IMAGES_BASE}/{img}"
        alt = alts[i] if i < len(alts) else ""
        html += f'\n<img src="{img}" alt="{alt}" style="{IMG_STYLE}">\n'
    return html

# ─── Markdown-Generierung ─────────────────────────────────────────────────────

FRONTMATTER_DE = """---
title: "{title}"
description: "{title} – GREMAC Betriebsanleitung"
lang: de
slug: {slug}
generated: "{ts}"
_note: "NICHT MANUELL BEARBEITEN – generiert von build_manuals.py aus PocketBase"
---
"""

FRONTMATTER_EN = """---
title: "{title}"
description: "{title} – GREMAC Operating Manual"
lang: en
slug: {slug}
generated: "{ts}"
_note: "DO NOT EDIT MANUALLY – generated by build_manuals.py from PocketBase"
---
"""

HEADER_DE = """<div style="background:linear-gradient(135deg,#058B8C,#047272);color:#fff;padding:40px 30px;border-radius:12px;margin-bottom:30px;">
<h2 style="color:#fff;font-size:1.8rem;font-weight:300;margin-bottom:8px;">{title}</h2>
<p style="opacity:.9;font-size:.95rem;margin:0;">{subtitle}</p>
</div>

<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:30px;padding-bottom:15px;border-bottom:2px solid #058B8C;">
<a href="/betriebsanleitungen/" style="color:#058B8C;text-decoration:none;font-size:.9rem;font-weight:500;">← Alle Betriebsanleitungen</a>
<div style="display:flex;gap:8px;flex-wrap:wrap;">
<a href="/en/betriebsanleitungen/{slug}/" style="background:#f0f9f9;border:2px solid #058B8C;border-radius:25px;padding:.35rem 1rem;color:#058B8C;text-decoration:none;font-size:.85rem;font-weight:600;">🇬🇧 English</a>
<button onclick="window.print()" style="background:#6C7059;border:none;border-radius:25px;padding:.35rem 1rem;color:#fff;font-size:.85rem;font-weight:600;cursor:pointer;">📄 Als PDF drucken</button>
</div>
</div>
"""

HEADER_EN = """<div style="background:linear-gradient(135deg,#058B8C,#047272);color:#fff;padding:40px 30px;border-radius:12px;margin-bottom:30px;">
<h2 style="color:#fff;font-size:1.8rem;font-weight:300;margin-bottom:8px;">{title}</h2>
<p style="opacity:.9;font-size:.95rem;margin:0;">{subtitle}</p>
</div>

<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:30px;padding-bottom:15px;border-bottom:2px solid #058B8C;">
<a href="/en/betriebsanleitungen/" style="color:#058B8C;text-decoration:none;font-size:.9rem;font-weight:500;">← All Operating Manuals</a>
<div style="display:flex;gap:8px;flex-wrap:wrap;">
<a href="/betriebsanleitungen/{slug}/" style="background:#f0f9f9;border:2px solid #058B8C;border-radius:25px;padding:.35rem 1rem;color:#058B8C;text-decoration:none;font-size:.85rem;font-weight:600;">🇩🇪 Deutsch</a>
<button onclick="window.print()" style="background:#6C7059;border:none;border-radius:25px;padding:.35rem 1rem;color:#fff;font-size:.85rem;font-weight:600;cursor:pointer;">📄 Print as PDF</button>
</div>
</div>
"""

def heading_tag(level, text_de, text_en, lang):
    text = text_de if lang == "de" else text_en
    if not text:
        return ""
    if level == 1:
        style = "color:#058B8C;border-bottom:2px solid #058B8C;padding-bottom:.5rem;margin:2.5rem 0 1rem;"
    else:
        style = "color:#6C7059;margin:1.5rem 0 .75rem;font-size:1.05rem;font-weight:600;"
    tag = "h2" if level == 1 else "h3"
    anchor = text.replace(" ", "_").replace("/", "_").replace("+", "plus")
    return f'\n<{tag} style="{style}"><a id="{anchor}"></a>{text}</{tag}>\n'

def generate_markdown(manual, blocks_ordered, lang):
    """Generiert vollständiges Markdown für ein Manual in einer Sprache."""
    slug = manual["slug"].replace("gremac-", "")  # z.B. "ezero", "e1"
    title_de = manual["title_de"]
    title_en = manual["title_en"]
    title = title_de if lang == "de" else title_en
    
    ts = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    fm = (FRONTMATTER_DE if lang == "de" else FRONTMATTER_EN).format(
        title=title, slug=slug, ts=ts
    )
    
    # Subtitle aus erstem Block-Titel ableiten (falls vorhanden)
    subtitle = title
    header = (HEADER_DE if lang == "de" else HEADER_EN).format(
        title=title, subtitle=subtitle, slug=slug
    )
    
    content_parts = [fm, header]
    
    for entry in blocks_ordered:
        block = entry["block"]
        level = entry.get("heading_level", 2)
        
        title_b_de = block.get("title_de", "")
        title_b_en = block.get("title_en", "")
        content = block.get(f"content_{lang}", "") or ""
        images = block.get("images")
        alt_de = block.get("image_alt_de", "")
        alt_en = block.get("image_alt_en", "")
        
        # Überschrift
        if title_b_de or title_b_en:
            content_parts.append(heading_tag(level, title_b_de, title_b_en, lang))
        
        # Inhalt
        if content.strip():
            content_parts.append("\n" + content.strip() + "\n")
        
        # Bilder nach dem Textinhalt
        img_html = render_images(images, alt_de, alt_en, lang)
        if img_html:
            content_parts.append(img_html)
    
    return "\n".join(content_parts)

# ─── Hauptlogik ───────────────────────────────────────────────────────────────

def main():
    no_build = "--no-build" in sys.argv
    
    print("🔐 PocketBase Auth...")
    token = get_token()
    
    print("📚 Lade Manuals...")
    manuals = get_all_records("kb_manuals", token)
    manuals = [m for m in manuals if m.get("published", True)]
    print(f"   {len(manuals)} Manuals gefunden")
    
    print("🧱 Lade Blöcke...")
    all_blocks = get_all_records("kb_blocks", token)
    blocks_by_id = {b["id"]: b for b in all_blocks}
    print(f"   {len(all_blocks)} Blöcke geladen")
    
    print("🔗 Lade Struktur...")
    structure = get_all_records("kb_structure", token)
    print(f"   {len(structure)} Struktur-Einträge geladen")
    
    # Struktur nach Manual gruppieren
    manual_structure = {}
    for entry in structure:
        mid = entry["manual"]
        manual_structure.setdefault(mid, []).append(entry)
    
    # Pro Manual sortieren
    for mid in manual_structure:
        manual_structure[mid].sort(key=lambda x: x.get("sort_order", 0))
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    generated = []
    
    for manual in manuals:
        mid = manual["id"]
        slug_full = manual["slug"]  # z.B. "gremac-ezero"
        slug = slug_full.replace("gremac-", "")  # z.B. "ezero"
        
        print(f"\n📖 Manual: {slug_full}")
        
        # Blöcke in Reihenfolge mit Block-Daten
        entries = manual_structure.get(mid, [])
        blocks_ordered = []
        for entry in entries:
            bid = entry["block"]
            block = blocks_by_id.get(bid)
            if block:
                blocks_ordered.append({
                    "block": block,
                    "heading_level": entry.get("heading_level", 2),
                    "sort_order": entry.get("sort_order", 0)
                })
        
        print(f"   {len(blocks_ordered)} Blöcke")
        
        for lang in ["de", "en"]:
            md = generate_markdown(manual, blocks_ordered, lang)
            out_path = os.path.join(OUTPUT_DIR, f"{slug}.{lang}.md")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(md)
            print(f"   ✅ {out_path}")
            generated.append(out_path)
    
    print(f"\n✅ {len(generated)} Markdown-Dateien generiert")
    
    if not no_build:
        print("\n🔨 Hugo Build...")
        result = subprocess.run(
            ["hugo", "--minify"],
            cwd=HUGO_ROOT,
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print("✅ Hugo Build erfolgreich")
            # Letzte Zeile mit Statistik
            for line in result.stdout.splitlines()[-3:]:
                print("   ", line)
        else:
            print("❌ Hugo Build fehlgeschlagen:")
            print(result.stderr)
            sys.exit(1)
    
    print("\n🎉 Fertig!")

if __name__ == "__main__":
    main()
